In [1]:
import numpy as np

In [2]:
import numpy as np
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [3]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [6]:
print(a1.dtype)
print(a2.dtype)

int32
float64


In [7]:
# anray()에 리스트 데이터를 직접 넣어서 배열 객체를 생성
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [8]:
# 1차원 배열을 생성했는데 NumPy는 다차원 배열도 생성
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
a = np.arange(0, 10, 2)
b = np.arange(1, 10)
c = np.arange(5)
print(a)
print(b)
print(c)

[0 2 4 6 8]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [11]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [13]:
b2 = np.arange(5)
b2.shape

(5,)

In [15]:
# 범위의 시작과 끝을 지정하고 데이터의 개수를 지정해 NumPy 배열을 생성하는 linspace()
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
# 사용한 'np.pi'는 NumPy메서 파이를 입력할 때 이용
np.linspace(0, np.pi, 20 )

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [22]:
# NumPy 배열의 형 변환은 astype()으로 할 수 있음
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [24]:
# rand() 함수는 (0,1)의 실수 난수를 갖는 NumPy 배열을 생성
np.random.rand(2,3)

array([[0.85600496, 0.92956486, 0.97788201],
       [0.26930437, 0.29181755, 0.29358238]])

In [25]:
np.random.rand(2,3,4)

array([[[0.89602341, 0.99377356, 0.71054103, 0.97611413],
        [0.41637864, 0.18804795, 0.63357397, 0.89536748],
        [0.9883739 , 0.76381377, 0.92671699, 0.59993998]],

       [[0.50717077, 0.79984949, 0.05305822, 0.23366573],
        [0.03878749, 0.92511133, 0.02314901, 0.35460654],
        [0.80534694, 0.28583345, 0.53925827, 0.46332007]]])

In [26]:
np.random.randint(10, size=(3, 4))

array([[9, 5, 2, 3],
       [0, 9, 5, 2],
       [4, 1, 8, 4]])

In [27]:
np.random.randint(1, 30)

6

In [28]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [29]:
arr1 + arr2

array([11, 22, 33, 44])

In [30]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [31]:
arr2 * 2

array([2, 4, 6, 8])

In [32]:
arr2 ** 2

array([ 1,  4,  9, 16])

In [33]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [34]:
arr1 / arr2

array([10., 10., 10., 10.])

In [35]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [36]:
arr1 > 20

array([False, False,  True,  True])

In [37]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [38]:
# 배열의 합(sum())과 평균(meant))을 구해보기로 함
a = [arr3.sum(), arr3.mean()]

# 배열의 표준 편차(std())와 분산(var())을 구하겠음
b = [arr3.std(), arr3.var()]

# 배열의 최솟값(min())과 최댓값(Max())을 구함
c = [arr3.min(), arr3.max()]

print(a, b, c, end='')

[10, 2.0] [1.4142135623730951, 2.0] [0, 4]

In [39]:
arr4 = np.arange(1,5)
arr4

# arr4를 이용해 누적 합(cumsum())과 누적 곱{cumprod())을 구함
a = arr4.cumsum()
b = arr4.cumprod()

print(a, b)

[ 1  3  6 10] [ 1  2  6 24]


In [40]:
# 행렬 연산을 하기 위해 2 x 2 행렬 A와 B를 만들겠음
A = np.array([0, 1, 2, 3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [41]:
B = np.array([3, 2, 0, 1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [44]:
# 행렬 A와 B를 이용한 행렬 곱의 예
a = A.dot(B)
b = np.dot(A,B)

print(a)
print(b)

[[0 1]
 [6 7]]
[[0 1]
 [6 7]]


In [45]:
# 행렬 A의 전치 행렬을 구하는 예
a = np.transpose(A)
b = A.transpose()

print(a)
print(b)

[[0 2]
 [1 3]]
[[0 2]
 [1 3]]


In [46]:
# 행렬 A의 역행렬을 구하기
a = np.linalg.inv(A)

# 행렬 A의 행렬식을 구하기
b = np.linalg.det(A)

print(a)
print(b)

[[-1.5  0.5]
 [ 1.   0. ]]
-2.0


In [2]:
import numpy as np

a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [3]:
a1[0]

0

In [4]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [5]:
a2[0, 2]

30

In [6]:
# 조건을 지정해 조건에 맞는 배열의 원소만 선택하는 예
a = np.array([1, 2, 3, 4, 5, 6])
a[a > 3]

array([4, 5, 6])

In [7]:
a[(a % 2) == 0]

array([2, 4, 6])

In [8]:
b1 = np.array([0, 10, 20, 30, 40, 50])

In [9]:
b1[1:4]

array([10, 20, 30])

In [11]:
b2 = np.arange(10, 100, 10).reshape(3, 3)

In [12]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [13]:
import pandas as pd

In [14]:
s1 = pd.Series([10, 20, 30, 40, 50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [15]:
s1.index
print(s1.index)

RangeIndex(start=0, stop=5, step=1)


In [16]:
s1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [17]:
s2 = pd.Series(['a', 'b', 'c', 1, 2, 3])
s2

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object

In [18]:
import numpy as np
s3 = pd.Series([np.nan,10,30])
s3

0     NaN
1    10.0
2    30.0
dtype: float64

In [19]:
index_date = ['2018-08-07','2018-10-08','2018-10-09','2018-10-10']
s4 = pd.Series([200, 195, np.nan, 205], index = index_date)
s4

2018-08-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
dtype: float64

In [20]:
s5 = pd.Series({'국어': 100, '영어': 95, '수학': 90})
s5

국어    100
영어     95
수학     90
dtype: int64

In [21]:
# 시작 날짜와 끝 날짜를 지정해 날짜 데이터를 생성
import pandas as pd
pd.date_range(start='2019-01-01',end='2019-01-07')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [22]:
pd.date_range(start='2019/01/01',end='2019.01.07')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [23]:
pd.date_range(start='01-01-2019',end='01/07/2019')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [24]:
pd.date_range(start='2019-01-01', periods = 7)

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [25]:
pd.date_range(start='2019-01-01', periods = 4, freq = '2D')

DatetimeIndex(['2019-01-01', '2019-01-03', '2019-01-05', '2019-01-07'], dtype='datetime64[ns]', freq='2D')

In [28]:
print('xxxx')

xxxx


In [26]:
import pandas as pd

pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [30]:
import numpy as np
import pandas as pd

data_list = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
pd.DataFrame(data_list)

0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [31]:
# data 뿐만 아니라 index와 columns도 지정

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8 ,9], [10, 11, 12]])
index_date = pd.date_range('2019-09-01', periods=4)
columns_list = ['A', 'B', 'C']
pd.DataFrame(data, index=index_date, columns=columns_list)

A   B   C
2019-09-01   1   2   3
2019-09-02   4   5   6
2019-09-03   7   8   9
2019-09-04  10  11  12

In [32]:
# 딕셔너리 타입으로 2차원 데이터 입력

table_data = {'연도':[2015, 2016, 2016, 2017, 2017],
             '지사':['한국', '한국', '미국', '한국', '미국'],
             '고객 수':[200, 250, 450, 300, 500]}

table_data

{'연도': [2015, 2016, 2016, 2017, 2017],
 '지사': ['한국', '한국', '미국', '한국', '미국'],
 '고객 수': [200, 250, 450, 300, 500]}

In [33]:
pd.DataFrame(table_data)

연도  지사  고객 수
0  2015  한국   200
1  2016  한국   250
2  2016  미국   450
3  2017  한국   300
4  2017  미국   500

In [34]:
# 데이터 연산
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])
s1+s2

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [35]:
s1-s2

0    -9
1   -18
2   -27
3   -36
4   -45
dtype: int64

In [37]:
# 파이썬 리스트와 달리 pandas 데이터끼리는 서로 크기가 달라도 연산할 수 있다.
# 연산할 수 없는 값은 NaN 표시
s3 = pd.Series([1, 2, 3, 4])
s4 = pd.Series([10, 20, 30, 40, 50])

s3+s4

0    11.0
1    22.0
2    33.0
3    44.0
4     NaN
dtype: float64

In [38]:
# 데이터프레임끼리도 연산 가능
table1 = {'a':[1,2,3,4,5],
         'b':[10, 20, 30, 40, 50],
         'c':[100, 200, 300, 400, 500]}
table2 = {'a':[1,2,3],
         'b':[10, 20, 30],
         'c':[100, 200, 300]}

df1 = pd.DataFrame(table1)
df2 = pd.DataFrame(table2)

# 길이가 달라도 연산 가능
df1+df2

a     b      c
0  2.0  20.0  200.0
1  4.0  40.0  400.0
2  6.0  60.0  600.0
3  NaN   NaN    NaN
4  NaN   NaN    NaN

In [40]:
table_data3 = {'봄':  [256.5, 264.3, 215.9, 223.2, 312.8],
              '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
              '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
              '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]}
columns_list = ['봄', '여름', '가을', '겨울']
index_list = ['2012', '2013', '2014', '2015', '2016']

df3 = pd.DataFrame(table_data3, columns = columns_list, index=index_list)
df3

봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1

In [41]:
df3.mean()

봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64

In [42]:
df3.std()

봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64

In [44]:
# 연산 방향을 행 방향으로 설정
df3.mean(axis=1)

2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64

In [45]:
# 평균, 표준편차, 최솟값, 최댓값 한 번에
df3.describe()

봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.800000  770.600000  381.600000  139.300000

In [46]:
KTX_data = {'경부선 KTX': [39060, 39896, 42005, 43621, 41702, 41266, 32427],
            '호남선 KTX': [7313, 6967, 6873, 6626, 8675, 10622, 9228],
            '경전선 KTX': [3627, 4168, 4088, 4424, 4606, 4984, 5570],
            '전라선 KTX': [309, 1771, 1954, 2244, 3146, 3945, 5766],
            '동해선 KTX': [np.nan,np.nan, np.nan, np.nan, 2395, 3786, 6667]}
col_list = ['경부선 KTX','호남선 KTX','경전선 KTX','전라선 KTX','동해선 KTX']
index_list = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']

df_ktx = pd.DataFrame(KTX_data, columns= col_list, index= index_list)

In [47]:
df_ktx

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0
2016    41266    10622     4984     3945   3786.0
2017    32427     9228     5570     5766   6667.0

In [49]:
df_ktx.index

Index(['2011', '2012', '2013', '2014', '2015', '2016', '2017'], dtype='object')

In [50]:
df_ktx.columns

Index(['경부선 KTX', '호남선 KTX', '경전선 KTX', '전라선 KTX', '동해선 KTX'], dtype='object')

In [51]:
df_ktx.values

array([[39060.,  7313.,  3627.,   309.,    nan],
       [39896.,  6967.,  4168.,  1771.,    nan],
       [42005.,  6873.,  4088.,  1954.,    nan],
       [43621.,  6626.,  4424.,  2244.,    nan],
       [41702.,  8675.,  4606.,  3146.,  2395.],
       [41266., 10622.,  4984.,  3945.,  3786.],
       [32427.,  9228.,  5570.,  5766.,  6667.]])

In [52]:
df_ktx.head()

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN
2014    43621     6626     4424     2244      NaN
2015    41702     8675     4606     3146   2395.0

In [53]:
df_ktx[1:2]

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2012    39896     6967     4168     1771      NaN

In [54]:
df_ktx.loc['2011']

경부선 KTX    39060.0
호남선 KTX     7313.0
경전선 KTX     3627.0
전라선 KTX      309.0
동해선 KTX        NaN
Name: 2011, dtype: float64

In [55]:
df_ktx.loc['2011':'2013']

경부선 KTX  호남선 KTX  경전선 KTX  전라선 KTX  동해선 KTX
2011    39060     7313     3627      309      NaN
2012    39896     6967     4168     1771      NaN
2013    42005     6873     4088     1954      NaN

In [57]:
df_ktx[['경부선 KTX']]

경부선 KTX
2011    39060
2012    39896
2013    42005
2014    43621
2015    41702
2016    41266
2017    32427

In [60]:
df_ktx[['경부선 KTX']]['2012':'2014']

경부선 KTX
2012    39896
2013    42005
2014    43621

In [61]:
# 행렬에서 행과 열을 바꾸는 전치 (transpose) 를 구하려면?
df_ktx.T

2011     2012     2013     2014     2015     2016     2017
경부선 KTX  39060.0  39896.0  42005.0  43621.0  41702.0  41266.0  32427.0
호남선 KTX   7313.0   6967.0   6873.0   6626.0   8675.0  10622.0   9228.0
경전선 KTX   3627.0   4168.0   4088.0   4424.0   4606.0   4984.0   5570.0
전라선 KTX    309.0   1771.0   1954.0   2244.0   3146.0   3945.0   5766.0
동해선 KTX      NaN      NaN      NaN      NaN   2395.0   3786.0   6667.0