# 판다스 설명
- series, DataFrame등의 자료구조를 활용한 데이터 분석 기능을 제공해주는 라이브러리
- 시리즈(1차원 배열) 데이터프레임(2차원 행렬구조)

## 판다스의 목적
- 서로 다른 유형의 데이터를 공통된 포맷으로 정리하는 것

## series
- numpy의 ndarray를 기반으로 인덱싱 기능을 추가하여 1차원 배열을 나타냄



In [1]:
# import

import pandas as pd
import numpy as np

In [2]:
# series 생성하기 (리스트)
s = pd.Series([1,2,3])
s

0    1
1    2
2    3
dtype: int64

In [92]:
# (튜플)
s = pd.Series((1.0, 2.0, 3.0))
s

0    1.0
1    2.0
2    3.0
dtype: float64

In [93]:
s2 = pd.Series(['a', 'a', 'c'])
s2

0    a
1    a
2    c
dtype: object

In [94]:
# 리스트내에 서로 다른 type의 data가 있으면 형변환 일어남- 문자열로 변환됨
s_1 = pd.Series(['a',1,3.0]) #dtype: object
s_1

0      a
1      1
2    3.0
dtype: object

In [95]:
s = pd.Series(range(10,14)) # index 인수는 생략됨
s

0    10
1    11
2    12
3    13
dtype: int64

In [96]:
range(10, 14)

range(10, 14)

In [97]:
np.arange(200)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [98]:
s3 = pd.Series(np.arange(200))
s3

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int32

In [99]:
# NaN은 np.nan 속성을 이용해서 생성
s=pd.Series([1,2,3,np.nan,6,8])
s
# dtype: float64
# 판다스가 처리하는 자료구조인 시리즈와 데이터프레임에서 결측치가 있는 경우는 datatype이 float으로 변경

0    1.0
1    2.0
2    3.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [100]:
# 인덱스 명시해서 시리즈 만들기
s=pd.Series([10,20,30],index=[1,2,3])
s

1    10
2    20
3    30
dtype: int64

In [101]:
s= pd.Series([95,100,88], index = ['홍길동','이몽룡','성춘향'])
s

홍길동     95
이몽룡    100
성춘향     88
dtype: int64

In [102]:
s0=pd.Series([10,20,30],index=[1,2,3])
s0

1    10
2    20
3    30
dtype: int64

In [103]:
s0.index

Index([1, 2, 3], dtype='int64')

In [104]:
s00 = pd.Series([1, 2, 3]) # index를 명시하지 않음
s00.index # 범위 인덱스가 생성

RangeIndex(start=0, stop=3, step=1)

In [105]:
s= pd.Series([9904312,3448737,289045,2466052],
                    index=["서울","부산","인천","대구"])
s.index #Index(['서울', '부산', '인천', '대구'], dtype='object')

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [106]:
# 시리즈.index.name 속성 : 시리즈의 인덱스에 이름을 붙일 수 있음
s.index.name = '광역시'
s

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
dtype: int64

In [107]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')

In [108]:
s.values

array([9904312, 3448737,  289045, 2466052], dtype=int64)

In [109]:
s.name = '인구'
s

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64

- 인덱싱 : 데이터에서 특정한 데이터를 골라내는 것
- 인덱스를 별도 지정하지 않으면 0부터 시작하는 정수형 인덱스가 지정됨

In [110]:
print(s.index) # 문자열형 인덱스
s['인천'] # 문자형 인덱스로 접근
# s[2] # 위치 인덱스 사용 가능

Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')


289045

In [111]:
# 정수형 인덱스인 경우
s03 = pd.Series([1,2,3], index=[1,2,3])
s03
s03[1] # 명시적 인덱스(정수인덱스임) 사용
# s03[0] # 위치인덱스 접근 - KeyError
# 정수인덱스인 경우 위치인덱스는 사용 불가

1

In [112]:
# 문자형 인덱스(부산 데이터 추출)
s['부산']

3448737

In [113]:
# 두개 이상의 인덱싱 코드를 나열하면 - 튜플형태로 반환
s[3], s['대구']

C:\Users\user\AppData\Local\Temp\ipykernel_11068\4046422232.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[3], s['대구']


(2466052, 2466052)

In [114]:
# 노트북 팁
# 데이터에 두번 접근
s
s # 마지막 연산에 대해서만 접근 결과를 보여줌

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64

In [115]:
print(s)
# s[0,3,1] #KeyError: 'key of type tuple not found and not a MultiIndex'
s[0],s[3],s[1] #(9904312, 2466052, 3448737)
# 시리즈명[[인덱스리스트]] - 시리즈형태로 반환
s[[0,3,1]] #- 인덱스 리스트 내의 해당 인덱스의 item을 추출 후 시리즈 형태로 반환

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64


C:\Users\user\AppData\Local\Temp\ipykernel_11068\2510924453.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0],s[3],s[1] #(9904312, 2466052, 3448737)
C:\Users\user\AppData\Local\Temp\ipykernel_11068\2510924453.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[[0,3,1]] #- 인덱스 리스트 내의 해당 인덱스의 item을 추출 후 시리즈 형태로 반환


광역시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

- 시리즈 슬라이싱

In [116]:
print(s)
# s[[1,2]]
# s[['부산', '인천']]
s[1:3] # 시리즈 슬라이싱을 사용하면 시리즈로 반환

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64


광역시
부산    3448737
인천     289045
Name: 인구, dtype: int64

In [117]:
# 문자인덱스를 이용한 슬라이싱 가능
# 표시된 문자인덱스 범위 모두 추출
s["부산":"대구"]

광역시
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64

In [118]:
# 정수형 인덱스를 명시했을 경우
s_01 = pd.Series([100,200,300,400], index=[1,2,3,4])
print(s_01)
s_01[[2,3,4]]
# 슬라이싱 사용 - # 0-base 슬라이싱을 사용
s_01[2:4]
# 시리즈의 인덱스를 명시할때는 가급적이면 문자형으로 명시하는 것이 좋다

1    100
2    200
3    300
4    400
dtype: int64


3    300
4    400
dtype: int64

In [119]:
# 인덱스를 문자값으로 지정한 시리즈
s0 = pd.Series(range(3),index=['a','b','c'])
s0

a    0
b    1
c    2
dtype: int64

In [120]:
s0['a']
s0.a

0

In [121]:
print(s) # 한글문자 인덱스
s['서울']
s.서울

광역시
서울    9904312
부산    3448737
인천     289045
대구    2466052
Name: 인구, dtype: int64


9904312

In [122]:
# 인덱스를 통한 데이터 업데이트
s['서울'] = 10000000
s['서울']

10000000

In [123]:
s

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64

In [124]:
# 인덱스 재사용하기
print(s.index)
s1 = pd.Series(np.arange(4),s.index)
s1

Index(['서울', '부산', '인천', '대구'], dtype='object', name='광역시')


광역시
서울    0
부산    1
인천    2
대구    3
dtype: int32

## 시리즈 연산

In [125]:
# 문자 인덱스의 시리즈 s 확인 후 연산 실습
s
# 도시
# 서울 9904312
# 부산 3448737
# 인천 289045
# 대구 2466052
# Name: 인구, dtype: int64

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64

In [126]:
# 벡터화 연산(집합적 자료형의 원소 각각을 독립적으로 계산하는 방법)

# 시리즈 원소 각각에 대하여 + 4 연산을 진행 - 벡터화 연산
pd.Series([1,2,3]) + 4

0    5
1    6
2    7
dtype: int64

In [127]:
# s 시리즈의 단위가 커서 단위를 변경하고 자 함 1/1000000
# 시리즈 자체를 1000000으로 나누면 됨, 벡터화연산을 진행 함
print(s)
s/1000000 # 대입하지 않았음

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64


광역시
서울    10.000000
부산     3.448737
인천     0.289045
대구     2.466052
Name: 인구, dtype: float64

In [128]:
s

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64

In [129]:
# 벡터화 인덱싱도 가능
# 시리즈[조건]
# s시리즈 값 중 2500000 보다 크고 5000000보다 작은 원소를 추출
s[(s>250e4) & (s<500e4)]
# s 시리즈 각 원소값 각각에 대해서 조건식을 확인해서 결과가 True인 원소를 반환

광역시
부산    3448737
Name: 인구, dtype: int64

- Boolean selection
- boolean Series가 []와 함께 사용되면 True 값에 해당하는 값만 새로 반환되는 Series객체에 포함됨
- 다중조건의 경우, &(and), |(or)를 사용하여 연결 가능

In [130]:
s0 = pd.Series(np.arange(10), np.arange(10)+1)
s0

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [131]:
s0>5

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

In [132]:
s0[s0>5]

7     6
8     7
9     8
10    9
dtype: int32

In [133]:
# 짝수 값만 추출
s0[s0%2==0]

1    0
3    2
5    4
7    6
9    8
dtype: int32

In [134]:
# 인덱스에도 관계연산이 가능
s0.index > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [135]:
s0[s0.index>5]

6     5
7     6
8     7
9     8
10    9
dtype: int32

In [136]:
# s0의 value가 5를 초과하고 8미만인 아이템(원소)만 추출하시오
s0[(s0>5) & (s0<8)]

7    6
8    7
dtype: int32

In [137]:
(s0 >= 7).sum() # True의 개수 총 합

3

In [138]:
(s0[s0 >= 7]).sum() # 조건의 결과가 True인 원소들의 합

24

In [139]:
# 두 시리즈간의 연산
num_s1=pd.Series([1,2,3,4],index=['a','b','c','d'])
num_s1

a    1
b    2
c    3
d    4
dtype: int64

In [140]:
num_s2=pd.Series([5,6,7,8],index=['b','c','d','a'])
num_s2

b    5
c    6
d    7
a    8
dtype: int64

In [141]:
num_s1 + num_s2 # 시리즈간의 연산은 같은 인덱스를 찾아 연산을 진행함

a     9
b     7
c     9
d    11
dtype: int64

In [142]:
num_s3=pd.Series([5,6,7,8],index=['e','b','f','g'])
num_s4=pd.Series([1,2,3,4],index=['a','b','c','d'])

In [143]:
# 동일한 인덱스는 연산을 진행하고 나머지 인덱스는 연산처리가 불가능 해서 NaN값으로 처리
num_s3 - num_s4

a    NaN
b    4.0
c    NaN
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [144]:
num_s3.values - num_s4.values
# values 속성을 사용해 값만을 추출해 연산을 진행하게 되면 시리즈의 형태가 사라지므로
# 동일 위치 원소들끼리 연산을 진행
# 시리즈.values는 array 형태 반환

array([4, 4, 4, 4], dtype=int64)

딕셔너리와 시리즈의 관계

- 시리즈 객체는 라벨에 의해 인덱싱이 가능함
- 실질적으로는 라벨을 key로 가지는 딕셔너리 형과 같다고 볼 수 있음
- 딕셔너리에서 제공하는 대부분의 연산자 사용 가능

In [145]:
s

광역시
서울    10000000
부산     3448737
인천      289045
대구     2466052
Name: 인구, dtype: int64

In [146]:
# 인덱스가 서울인 원소가 시리즈에 있는지 확인
'서울' in s

True

In [147]:
'대전' in s

False

In [148]:
'대전' not in s

True

In [149]:
# 딕셔너리의 items() 함수 시리즈에 사용 가능
s.items() # zip 객체

In [150]:
list(s.items())

[('서울', 10000000), ('부산', 3448737), ('인천', 289045), ('대구', 2466052)]

In [151]:
# 시리즈 각 원소 출력
for k, v in s.items():
    print('%s=%d'%(k, v))

서울=10000000
부산=3448737
인천=289045
대구=2466052


딕셔너리로 시리즈 만들기
- Series({key:value,key1:value1....})
- 인덱스 -> key
- 값 -> value

In [152]:
scores = {'홍길동':96, '이몽룡':100, '성춘향':88}
s=pd.Series(scores)
s

홍길동     96
이몽룡    100
성춘향     88
dtype: int64

In [153]:
city = {'서울':9631482,'부산':3393191,'인천':2632035,'대전':1490158}
s=pd.Series(city)
s

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

- 딕셔너리의 원소는 순서를 갖지 않는다.
- 딕셔너리로 생성된 시리즈의 원소도 순서가 보장되지 않는다.
- 만약 순서를 보장하고 싶으면 인덱스를 리스트로 지정해야 한다.

In [154]:
city = {'서울':9631482,'부산':3393191,'인천':2632035,'대전':1490158}
s=pd.Series(city,index=city.keys())
s

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [155]:
s=pd.Series(city, index=['부산','인천','서울','대전'])
s

부산    3393191
인천    2632035
서울    9631482
대전    1490158
dtype: int64

시리즈 데이터의 갱신,추가, 삭제
- 인덱싱을 이용하면 딕셔너리 처럼 갱신, 추가 가능

In [156]:
s

부산    3393191
인천    2632035
서울    9631482
대전    1490158
dtype: int64

In [157]:
# s 시리즈의 부산의 인구 값을 1630000으로 변경
s['부산'] = 1630000
s

부산    1630000
인천    2632035
서울    9631482
대전    1490158
dtype: int64

In [158]:
# 시리즈 내 원소 삭제 - del 명령어
del s['서울']
s

부산    1630000
인천    2632035
대전    1490158
dtype: int64

In [159]:
# 시리즈에 새로운 원소 추가
s['대구'] = 1875000

In [160]:
s

부산    1630000
인천    2632035
대전    1490158
대구    1875000
dtype: int64

Series 함수
- size, shape, unique, count, value_counts 함수
- size : 개수 반환
- shape : 튜플 형태로 shape 반환
- unique : 유일한 값만 ndarray로 반환
- count : NaN을 제외한 개수를 반환
- mean : NaN을 제외한 평균
- value_counts : NaN을 제외하고 각 값들의 빈도를 반환

In [161]:
s1 = pd.Series([1, 1, 2, 1, 2, 2, 2, 1, 1, 3, 3, 4, 5, 5, 7, np.NaN])
s1

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [162]:
len(s1)

16

In [163]:
s1.size

16

In [164]:
s1.shape # 차원으로 표현하기 때문에 튜플형태로 출력

(16,)

In [165]:
s1.unique() # nan도 하나의 값으로 보고 표현되어짐

array([ 1.,  2.,  3.,  4.,  5.,  7., nan])

In [166]:
s1.count() # nan을 제외한 원소의 개수

15

In [168]:
a = np.array([2,2,2,2,np.NaN]) # array 타입
print(a.mean()) # array에 대해 mean() 적용하면 nan이 포함된 계산을 진행 - nan이 반환

b=pd.Series(a) # 배열을 시리즈로 변경
print(b)
b.mean() # NaN 빼고 계산

nan
0    2.0
1    2.0
2    2.0
3    2.0
4    NaN
dtype: float64


2.0

In [169]:
s1

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [170]:
s1.mean()

2.6666666666666665

In [171]:
s1.value_counts()
# 각 원소들에 대해 동일값의 원소끼리 그룹핑하여 개수를 세서 반환하는 함수

1.0    5
2.0    4
3.0    2
5.0    2
4.0    1
7.0    1
Name: count, dtype: int64

날짜 자동 생성 : date_range

In [172]:
# 날짜 인덱스를 이용하여 시리즈 만들기
# 날짜 표시 : '년-월-일' 형태의 문자열로 표시
index_date = ['2018-10-07','2018-10-08','2018-10-09','2018-10-10']
s4 = pd.Series([200,195,np.nan,205],index = index_date)
s4

2018-10-07    200.0
2018-10-08    195.0
2018-10-09      NaN
2018-10-10    205.0
dtype: float64

In [173]:
type(s4.index[0]) # str

str

- 판다스 패키지의 date_range 함수 (날짜생성)
    - pd.date_range(start=None, end=None, periods=None, freq='D')
    - start : 시작날짜/ end= 끝날짜 / periods = 날짜 생성기간/ fref = 날짜 생성 주기
    - start는 필수 옵션/end나 periods는 둘 중 하나가 있어야 함/ freq는 기본 Day로 설정

In [174]:
pd.date_range(start='2018-10-01', end='2018-10-20')
# DatetimeIndex 반환
# dtype='datetime64[ns]'

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08',
               '2018-10-09', '2018-10-10', '2018-10-11', '2018-10-12',
               '2018-10-13', '2018-10-14', '2018-10-15', '2018-10-16',
               '2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20'],
              dtype='datetime64[ns]', freq='D')

In [175]:
pd.date_range(start='2018-10-01', end='2018-10-20', freq='d')
#freq='d' 기본 값

DatetimeIndex(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08',
               '2018-10-09', '2018-10-10', '2018-10-11', '2018-10-12',
               '2018-10-13', '2018-10-14', '2018-10-15', '2018-10-16',
               '2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20'],
              dtype='datetime64[ns]', freq='D')

In [176]:
pd.date_range(start='2018-10-01', end='2018-10-20', freq='3D') # 3일씩 증가

DatetimeIndex(['2018-10-01', '2018-10-04', '2018-10-07', '2018-10-10',
               '2018-10-13', '2018-10-16', '2018-10-19'],
              dtype='datetime64[ns]', freq='3D')

In [180]:
pd.date_range(start='2018-10-01', end='2018-10-20', freq='W')
# 2018-10-01일을 기준으로 1주일씩 증가하는 날짜
# 1주 시작일 일요일을 표시
# 2018년 10월 1일 - 월요일

DatetimeIndex(['2018-10-07', '2018-10-14'], dtype='datetime64[ns]', freq='W-SUN')

In [181]:
# 2018년 10월 1일 이후 일요일 날짜 4개 생성
pd.date_range(start='2018-10-01', periods=4, freq='W')

DatetimeIndex(['2018-10-07', '2018-10-14', '2018-10-21', '2018-10-28'], dtype='datetime64[ns]', freq='W-SUN')

In [182]:
# 2018-10-01일 이후 월의 마지막 날짜 4개 생성
pd.date_range(start='2018-10-01', periods=4, freq='ME')

DatetimeIndex(['2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31'], dtype='datetime64[ns]', freq='ME')

In [184]:
pd.date_range(start='2018-10-01', periods=4, freq='MS')

DatetimeIndex(['2018-10-01', '2018-11-01', '2018-12-01', '2019-01-01'], dtype='datetime64[ns]', freq='MS')

In [186]:
pd.date_range(start='2018-10-01', periods=12, freq='BME')
# '2BM' 업무일 기준 2개월 간격 월말 주기

DatetimeIndex(['2018-10-31', '2018-11-30', '2018-12-31', '2019-01-31',
               '2019-02-28', '2019-03-29', '2019-04-30', '2019-05-31',
               '2019-06-28', '2019-07-31', '2019-08-30', '2019-09-30'],
              dtype='datetime64[ns]', freq='BME')

In [187]:
pd.date_range(start='2018-10-01', periods=4, freq='QS')
# 분기 시작일 기준

DatetimeIndex(['2018-10-01', '2019-01-01', '2019-04-01', '2019-07-01'], dtype='datetime64[ns]', freq='QS-JAN')

In [189]:
pd.date_range(start='2018-10-01', periods=4, freq='YS')
# 2018년 10월 1일 이후 연도 시작일 4개 생성

DatetimeIndex(['2019-01-01', '2020-01-01', '2021-01-01', '2022-01-01'], dtype='datetime64[ns]', freq='YS-JAN')

In [192]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq='h')

DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 09:00:00',
               '2018-01-20 10:00:00', '2018-01-20 11:00:00',
               '2018-01-20 12:00:00', '2018-01-20 13:00:00',
               '2018-01-20 14:00:00', '2018-01-20 15:00:00',
               '2018-01-20 16:00:00', '2018-01-20 17:00:00'],
              dtype='datetime64[ns]', freq='h')

In [194]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq='bh')
# 업무시간 기준 9 to 5로 설정

DatetimeIndex(['2018-01-22 09:00:00', '2018-01-22 10:00:00',
               '2018-01-22 11:00:00', '2018-01-22 12:00:00',
               '2018-01-22 13:00:00', '2018-01-22 14:00:00',
               '2018-01-22 15:00:00', '2018-01-22 16:00:00',
               '2018-01-23 09:00:00', '2018-01-23 10:00:00'],
              dtype='datetime64[ns]', freq='bh')

In [195]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq='30min')

DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 08:30:00',
               '2018-01-20 09:00:00', '2018-01-20 09:30:00',
               '2018-01-20 10:00:00', '2018-01-20 10:30:00',
               '2018-01-20 11:00:00', '2018-01-20 11:30:00',
               '2018-01-20 12:00:00', '2018-01-20 12:30:00'],
              dtype='datetime64[ns]', freq='30min')

In [198]:
pd.date_range(start='2018-1-20 08:00', periods=10, freq='10s')

DatetimeIndex(['2018-01-20 08:00:00', '2018-01-20 08:00:10',
               '2018-01-20 08:00:20', '2018-01-20 08:00:30',
               '2018-01-20 08:00:40', '2018-01-20 08:00:50',
               '2018-01-20 08:01:00', '2018-01-20 08:01:10',
               '2018-01-20 08:01:20', '2018-01-20 08:01:30'],
              dtype='datetime64[ns]', freq='10s')