In [1]:
# 설정변경코드
# 변수 명이 두 번 이상 출력되어도 모두 콘솔에서 보여줄 것
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

# InteractiveShell.ast_node_interactivity : 'all' | 'last' | 'last_expr' | 'none' (기본값은 'last_expr')

In [2]:
import numpy as np
import pandas as pd

### panda 데이터처리 및 변환관련 함수
데이터 개수 세기
- count() 함수 이용
- NaN값은 세지 않는다

In [3]:
# 시리즈에서 개수 세기
s = pd.Series(range(10))
s[3] = np.nan
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [4]:
s.count() # 널값 제외하고 카운트

9

### 데이터 프레임에 count() 함수 적용하기
- 각 열마다 데이터 개수를 세기 때문에 누락된 부분을 찾을 때 유용

난수 발생시켜 dataframe 생성


In [5]:
np.random.randint(5) # 정수 0~4사이에서 난수 발생
np.random.randint(5, size =4) # 난수 4개를 생성

4

array([3, 1, 2, 4])

In [6]:
# 난수 발생시 항상 고정된 값을 발생시킬 수도 있음
np.random.seed(3)
np.random.randint(5, size =4) # 난수 4개를 생성

array([2, 0, 1, 3])

In [7]:
# 위 셀에서 고정시켰지만 한번 사용했으므로 seed 는 리셋됨
np.random.randint(5, size =4)

array([0, 0, 0, 3])

In [8]:
# 시드값이 매번 다르게 전달되도록 코드를 작성
import time
np.random.seed(int(time.time()))
np.random.randint(5, size=4)

array([2, 2, 2, 0])

In [9]:
np.random.randint(5,size=(4,4))

array([[2, 0, 0, 4],
       [4, 0, 2, 2],
       [4, 0, 4, 4],
       [4, 0, 4, 3]])

In [10]:
np.random.seed(3) # 시드값 고정되어서 동일한 값의 난수가 발생
df1=pd.DataFrame(np.random.randint(5,size=(4,4))) #기본 정수
df1.iloc[2,3] =np.nan # 2행3열의 value는 NaN으로 변경 - 3열 데이터는 실수형으로 변환됨
df1
# 컬럼(피처)은 동일한 타입의 데이터로만 구성할 수 있다

0  1  2    3
0  2  0  1  3.0
1  0  0  0  3.0
2  2  3  1  NaN
3  2  0  4  4.0

In [11]:
# 각 열에 대한 원소의 개수 반환
# 3열은 3개라면 결측치가 있음
df1.count()

0    4
1    4
2    4
3    3
dtype: int64

count 함수 사용 예제

In [13]:
import seaborn as sns # 그래프 패키지

# 타이타닉 승객 데이터 로드
titanic = pd.read_csv('./data/test.csv')
del titanic['Unnamed: 0']
titanic.head(10)
titanic.tail(2)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

survived  pclass   sex   age  sibsp  parch   fare embarked  class  who  \
889         1       1  male  26.0      0      0  30.00        C  First  man   
890         0       3  male  32.0      0      0   7.75        Q  Third  man   

     adult_male deck embark_town alive  alone  
889        True    C   Cherbourg   yes   True  
890        True  NaN  Queenstown    no   True

In [14]:
titanic.to_csv('./data/test.csv')

In [16]:
titanic.count()
# 대부분의 열이 891개의 원소가 있는데 반해
# age는 714, deck 203개의 원소가 있음
# embarked 889개의 원소

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

카테고리 값 세기
- 시리즈의 값이 정수,문자열 등 카테고리 값인 경우에
- 시리즈.value_counts()메서드를 사용해 각각의 값이 나온 횟수를 셀 수 있음
- 파라미터 normalize=True 를 사용하면 각 값 및 범주형 데이터의 비율을 계산
- 시리즈.value_counts(normalize=True)

In [17]:
np.random.seed(1) #항상 같은 값이 나오게 설정
s2=pd.Series(np.random.randint(6,size=100))
s2.tail() # 시리즈의 뒷부분 데이터 5개를 추출
s2.head() # 시리즈의 앞부분 데이터 5개를 추출
s2.head(10) # 해당 개수 만큼의 데이터를 추출
len(s2)

95    4
96    5
97    2
98    4
99    3
dtype: int32

0    5
1    3
2    4
3    0
4    1
dtype: int32

0    5
1    3
2    4
3    0
4    1
5    3
6    5
7    0
8    0
9    1
dtype: int32

100

In [18]:
s2.value_counts() #0,1,2,3,4,5의 데이터가 몇번 나왔는지
s2.value_counts(normalize=True)

1    22
0    18
4    17
5    16
3    14
2    13
Name: count, dtype: int64

1    0.22
0    0.18
4    0.17
5    0.16
3    0.14
2    0.13
Name: proportion, dtype: float64

In [19]:
# titanic 데이터 alive열 : 생존여부가 yes/no로 표시되어 있음
titanic['alive'].dtype # 해당 열의 data type을 반환
titanic['alive'].value_counts()
titanic['alive'].value_counts(normalize=True)

dtype('O')

alive
no     549
yes    342
Name: count, dtype: int64

alive
no     0.616162
yes    0.383838
Name: proportion, dtype: float64

In [20]:
titanic['alive'].value_counts(normalize=True) *100

alive
no     61.616162
yes    38.383838
Name: proportion, dtype: float64

In [21]:
titanic[['sex','alive']].value_counts()

sex     alive
male    no       468
female  yes      233
male    yes      109
female  no        81
Name: count, dtype: int64